server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Authorization  # Evita loop de autenticação no auth-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=  # Passa o token JWT
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/products/**
          filters:
            - TokenRelay=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
