spring:
  application:
    name: auth-service
    spring:
  config:
    import: optional:configserver:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: authuser
    password: authpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: danilobarreto15@gmail.com
    password: fipl hlim vzzm mwej
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-very-secure-secret-key-here
  expiration: 86400000
